[project]
name = "wante"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "discord>=2.3.2",
    "dotenv>=0.9.9",
    "ipykernel>=7.0.1",
    "langchain==0.3.27",
    "langchain-core==0.3.79",
    "langchain-discord>=1.0.2",
    "langchain-discord-shikenso>=1.1.1",
    "langchain-openai==0.3.35",
    "pandas>=2.3.3",
]
